### ISSUE TITLE
Question (local and remote multiplayer)

### ISSUE THREAD

**Issue by gilgoldman** [Ilyaki/SplitScreen#10]
Hi @Ilyaki!
Trying to expose the local server that SplitScreen creates to external connections via Ngrok to enable local and remote multiplayer.   
Think it'll work?    
If not, any ideas on how to do this without changing your mod too much or breaking anything?   

Unrelated - this mod is very nicely written and is one of my favorites. Kudos!

**Comment by PortableGoogle** [comment]
I can't even get it to be able to join a multiplayer created by another instance, all instances seem to be the same so it can't join itself or join the same game another instance already joined.

**Comment by gilgoldman** [comment]
Resolved by update 1.5's multiplayer functionality, closed
