### ISSUE TITLE
Split Screen will break in SMAPI 2.6 beta 16

### ISSUE THREAD

**Issue by Pathoschild** [Ilyaki/SplitScreen#2]
SMAPI 2.6 beta 16 changes how input is handled internally. Split Screen uses reflection to access those internals, so it will break:
> ![](https://user-images.githubusercontent.com/230581/40892181-1fbc4efa-6761-11e8-874f-d07ab2874fe2.png)

Starting with beta 16, there's a [new input API](https://stardewvalleywiki.com/Modding:Modder_Guide/APIs/Input) you can use instead for reading the values, though you'll still need reflection to change the mouse state. There's a preview SMAPI build pinned in the #modding channel on Discord if you'd like to get the mod ready for its release.

**Comment by Ilyaki** [comment]
Thanks for the heads up :)
I have a fix now, so I should be ready when SMAPI 2.16 is out
