### ISSUE TITLE
Rumbling wrong controller (regression)

### ISSUE THREAD

**Issue by neozero** [Ilyaki/SplitScreen#4]
Hello. When making the changes at 8f60c784c275420206c015d2defa45a1096ebd11, you forgot to keep the fix from 225cbee36b225b91a4d23c554f6ec7eabc525b1d, right here:
https://github.com/Ilyaki/SplitScreen/commit/8f60c784c275420206c015d2defa45a1096ebd11#diff-59af208434726d11b3593c060fbf8616L67

Both players are rumbling only the first controller again.

This is fixed by just adding it back like this:
```c#
//Get player index if it is set in launch options, e.g. StardewModdingAPI.exe --log-path "third.txt" --player-index 3
this.playerIndexController = new PlayerIndexController(Environment.GetCommandLineArgs());

//This fixes StardewValley.Rumble rumbling the wrong controller
Game1.playerOneIndex = PlayerIndexController._PlayerIndex.GetValueOrDefault();
```

Thanks for the amazing mod!

**Comment by Ilyaki** [comment]
Thanks for reporting, it should be fixed in 4.0.1
